SELECT * FROM city ORDER BY city DESC LIMIT 10;
SELECT * FROM film WHERE title LIKE "%airplane%";
SELECT amount FROM payment WHERE amount = (SELECT MAX(amount) FROM payment) LIMIT 1;
SELECT COUNT(customer_id) FROM customer WHERE customer_id = 1;
SELECT * FROM payment INNER JOIN customer ON payment.customer_id = customer.customer_id WHERE customer.email = "NANCY.THOMAS@sakilacustomer.org";
SELECT * FROM film_list WHERE actors LIKE "%Bob Fawcett%";
CALL film_in_stock((SELECT film_id FROM film WHERE title = "Alien Center"), 2, @film_count);
START TRANSACTION;
	INSERT INTO staff(first_name, last_name, address_id, store_id, username) VALUES("Brianna", "Rodriguez", 1, 1, "Bri");
    SELECT @new_store_manager_id := MAX(staff_id) FROM staff;
	INSERT INTO store(manager_staff_id, address_id) VALUES(@new_store_manager_id, 1);
    SELECT @new_store_id := MAX(store_id) FROM store;
    UPDATE staff SET store_id = @new_store_id WHERE staff_id = @new_store_manager_id;
	COMMIT;
UPDATE store SET last_update = CURRENT_TIMESTAMP() WHERE store_id = @new_store_id;
START TRANSACTION;
	UPDATE staff SET store_id = 1 WHERE staff_id = @new_store_manager_id;
	DELETE FROM store WHERE store_id = @new_store_id;
    COMMIT;